(** CPS-style reagent combinators with composable swap channels.

    Unlike [03_stm]'s simpler reagent (a plain function
    ['a -> Xt.t -> 'b]), this reagent is a record that carries its
    continuation explicitly via the [seq] field. This is what makes
    channel [swap] composable — a swap posts its continuation to the
    channel, and a matching partner runs the continuation before
    committing the combined transaction.

    Based on the original reagents paper (Turon, PLDI 2012) and the
    reference implementation in [reference/reagents/]. *)

(* ──────────────────────────────────────────────────────────────────────────
   Types
   ────────────────────────────────────────────────────────────────────────── *)

(** Outcome of attempting to run a reagent. *)
type 'a result =
  | Done of 'a       (** Success: a value was produced. *)
  | Block            (** Permanent failure: precondition not met. *)
  | Retry            (** Transient failure: retry with fresh state. *)

(** A reagent transforming input ['a] to output ['b].

    - [try_react a xt]: attempt to run the reagent with input [a] and
      transaction log [xt]. Accumulates CAS/CMP ops in [xt].
    - [seq k]: compose with continuation [k]. Returns a new reagent that
      runs this reagent then passes its output to [k]. Channels use [seq]
      to pass the continuation to a matching partner. *)
type ('a, 'b) t = {
  try_react : 'a -> Xt.t -> 'b result;
  seq : 'c. ('b, 'c) t -> ('a, 'c) t;
}

type 'a ref = 'a Kcas.loc

(* ──────────────────────────────────────────────────────────────────────────
   Primitive reagent construction
   ────────────────────────────────────────────────────────────────────────── *)

(** [make_reagent f] builds a reagent from a try function.
    The [seq] field is generated by composing [f] with the continuation. *)
let rec make_reagent : type a b. (a -> Xt.t -> b result) -> (a, b) t =
  fun f -> {
    try_react = f;
    seq = fun k -> make_reagent (fun a xt ->
      match f a xt with
      | Done b -> k.try_react b xt
      | Block -> Block
      | Retry -> Retry)
  }

(* ──────────────────────────────────────────────────────────────────────────
   Ref operations
   ────────────────────────────────────────────────────────────────────────── *)

let ref v = Kcas.make v
let get r = Kcas.get r

let read r = make_reagent (fun () xt -> Done (Xt.get ~xt r))

let upd r f = make_reagent (fun b xt ->
  let v = Xt.get ~xt r in
  match f v b with
  | Some (v', c) -> Xt.set ~xt r v'; Done c
  | None -> Block)

let cas r expected desired = make_reagent (fun () xt ->
  let v = Xt.get ~xt r in
  if v = expected then (Xt.set ~xt r desired; Done ())
  else Block)

let modify r f = make_reagent (fun () xt -> Xt.modify ~xt r f; Done ())
let set r v = make_reagent (fun () xt -> Xt.set ~xt r v; Done ())

let constant v = make_reagent (fun _ _ -> Done v)
let lift f = make_reagent (fun a _ -> Done (f a))

(* ──────────────────────────────────────────────────────────────────────────
   Combinators
   ────────────────────────────────────────────────────────────────────────── *)

(** Sequential composition via the [seq] field. This is where the CPS
    structure matters — [r1.seq r2] lets [r1] know what comes after it,
    so primitives like [swap] can capture and forward the continuation. *)
let (>>) r1 r2 = r1.seq r2

(** Choice: try [r1]; on Block, try [r2]. *)
let rec (+) : type a b. (a, b) t -> (a, b) t -> (a, b) t =
  fun r1 r2 -> {
    try_react = (fun a xt ->
      match r1.try_react a xt with
      | Done _ as v -> v
      | Block -> r2.try_react a xt
      | Retry ->
        match r2.try_react a xt with
        | Done _ as v -> v
        | Block | Retry -> Retry);
    seq = (fun k -> (r1.seq k) + (r2.seq k));
  }

let pair r1 r2 = make_reagent (fun (a, b) xt ->
  match r1.try_react a xt with
  | Done c -> (match r2.try_react b xt with
               | Done d -> Done (c, d)
               | Block -> Block
               | Retry -> Retry)
  | Block -> Block
  | Retry -> Retry)

(* ──────────────────────────────────────────────────────────────────────────
   Execution
   ────────────────────────────────────────────────────────────────────────── *)

(** [run r a] executes reagent [r] with input [a]. Wraps [try_react] in
    [Xt.commit], so CAS/CMP ops are committed atomically. Blocks on
    [Block], retries on [Retry] (and on k-CAS interference). *)
let run r a =
  let rec loop () =
    match
      Xt.commit (fun ~xt ->
        match r.try_react a xt with
        | Done b -> Some b
        | Block -> Xt.retry ()
        | Retry -> None)
    with
    | Some b -> b
    | None -> loop ()
  in
  loop ()

(** [run_opt r a] executes [r]. Returns [Some b] on success, [None] on
    [Block] or [Retry]. Does not wait. *)
let run_opt r a =
  match
    Xt.commit (fun ~xt ->
      match r.try_react a xt with
      | Done b -> Some b
      | Block -> None
      | Retry -> None)
  with
  | v -> v
  | exception _ -> None
