(** CPS-style reagent combinators with composable swap channels.

    Unlike [03_stm]'s simpler reagent (a plain function
    ['a -> Xt.t -> 'b]), this reagent is a record that carries its
    continuation explicitly via the [seq] field. This is what makes
    channel [swap] composable — a swap posts its continuation to the
    channel, and a matching partner runs the continuation before
    committing the combined transaction.

    Execution uses a two-phase protocol:
    1. Without offer: try to complete synchronously. Channel swap returns
       [Block] if no partner. The [+] combinator can try alternatives.
    2. With offer: if phase 1 blocked, create an offer and try again.
       Channel swap posts the offer to its outgoing queue. When a partner
       arrives, they fulfill the offer and we wake up.

    Based on the original reagents paper (Turon, PLDI 2012). *)

(* ──────────────────────────────────────────────────────────────────────────
   Offers
   ────────────────────────────────────────────────────────────────────────── *)

(** An offer is a shared slot that can be:
    - Fulfilled with a value (by a channel partner on commit)
    - Signaled (by an awaiter firing on a read-set location change)
    The awaiting thread wakes up in either case. *)
type 'a offer_state =
  | Pending
  | Fulfilled of 'a
  | Signaled      (** A watched location changed; caller should retry. *)

type 'a offer = {
  mutable state : 'a offer_state;
  trigger : Trigger.t;
}

let make_offer () : 'a offer = {
  state = Pending;
  trigger = Trigger.create ();
}

(** [fulfill offer v] delivers [v] to the offer. *)
let fulfill (offer : 'a offer) (v : 'a) : bool =
  match offer.state with
  | Pending ->
    offer.state <- Fulfilled v;
    ignore (Trigger.signal offer.trigger);
    true
  | _ -> false

(** [signal_offer offer] wakes the awaiting fiber without delivering a value. *)
let signal_offer (offer : 'a offer) : unit =
  match offer.state with
  | Pending ->
    offer.state <- Signaled;
    ignore (Trigger.signal offer.trigger)
  | _ -> ()

let is_offer_pending (offer : 'a offer) : bool =
  match offer.state with Pending -> true | _ -> false

(** Suspend the fiber until the offer is fulfilled or signaled. *)
let await_offer_state (offer : 'a offer) : 'a offer_state =
  if offer.state = Pending then Trigger.await offer.trigger;
  let s = offer.state in
  s

(** Block until the offer is fulfilled with a value. Raises if signaled
    without a value (caller should retry). *)
let await_offer (offer : 'a offer) : 'a =
  match await_offer_state offer with
  | Fulfilled v -> v
  | Signaled -> failwith "await_offer: signaled without value"
  | Pending -> assert false

(* ──────────────────────────────────────────────────────────────────────────
   Reagent type
   ────────────────────────────────────────────────────────────────────────── *)

(** Outcome of attempting to run a reagent. *)
type 'a result =
  | Done of 'a       (** Success. *)
  | Block            (** Permanent failure: precondition not met. *)
  | Retry            (** Transient failure: retry with fresh state. *)

(** A reagent transforming input ['a] to output ['b].

    - [try_react a xt offer]: attempt to run. The optional offer is where
      the final ['b] will be delivered if the reagent blocks (e.g., swap
      posts this offer to the channel queue).
    - [seq k]: compose with continuation [k]. *)
type ('a, 'b) t = {
  try_react : 'a -> Xt.t -> 'b offer option -> 'b result;
  seq : 'c. ('b, 'c) t -> ('a, 'c) t;
}

type 'a ref = 'a Kcas.loc

(* ──────────────────────────────────────────────────────────────────────────
   Primitive reagent construction
   ────────────────────────────────────────────────────────────────────────── *)

(** [make_reagent f] builds a reagent from a try function. The [seq]
    field is generated by composing [f] with the continuation.

    When [seq k] is applied, the resulting reagent's [try_react] runs
    [f] with {i no} offer (since the offer is owned by the tail of the
    chain), then passes [f]'s output to [k.try_react] with the {i real}
    offer. This matches the reference implementation: only the operation
    at the tail (typically a swap) gets to see the offer. *)
let rec make_reagent : type a b. (a -> Xt.t -> b result) -> (a, b) t =
  fun f -> {
    try_react = (fun a xt _offer -> f a xt);
    seq = (fun k -> make_reagent_seq f k);
  }

and make_reagent_seq :
  type a b c. (a -> Xt.t -> b result) -> (b, c) t -> (a, c) t =
  fun f k -> {
    try_react = (fun a xt offer ->
      match f a xt with
      | Done b -> k.try_react b xt offer
      | Block -> Block
      | Retry -> Retry);
    seq = (fun k' -> make_reagent_seq f (compose k k'));
  }

and compose : type a b c. (a, b) t -> (b, c) t -> (a, c) t =
  fun r1 r2 -> r1.seq r2

(* ──────────────────────────────────────────────────────────────────────────
   Ref operations (none block, so offer is unused)
   ────────────────────────────────────────────────────────────────────────── *)

let ref v = Kcas.make v
let get r = Kcas.get r

let read r = make_reagent (fun () xt -> Done (Xt.get ~xt r))

let upd r f = make_reagent (fun b xt ->
  let v = Xt.get ~xt r in
  match f v b with
  | Some (v', c) -> Xt.set ~xt r v'; Done c
  | None -> Block)

let cas r expected desired = make_reagent (fun () xt ->
  let v = Xt.get ~xt r in
  if v = expected then (Xt.set ~xt r desired; Done ())
  else Block)

let modify r f = make_reagent (fun () xt -> Xt.modify ~xt r f; Done ())
let set r v = make_reagent (fun () xt -> Xt.set ~xt r v; Done ())

let constant v = make_reagent (fun _ _ -> Done v)
let lift f = make_reagent (fun a _ -> Done (f a))

(* ──────────────────────────────────────────────────────────────────────────
   Combinators
   ────────────────────────────────────────────────────────────────────────── *)

(** Sequential composition via the [seq] field. *)
let (>>) r1 r2 = r1.seq r2

(** Choice: try [r1]; on Block, try [r2]. *)
let rec (+) : type a b. (a, b) t -> (a, b) t -> (a, b) t =
  fun r1 r2 -> {
    try_react = (fun a xt offer ->
      match r1.try_react a xt offer with
      | Done _ as v -> v
      | Block -> r2.try_react a xt offer
      | Retry ->
        match r2.try_react a xt offer with
        | Done _ as v -> v
        | Block | Retry -> Retry);
    seq = (fun k -> (r1.seq k) + (r2.seq k));
  }

let pair r1 r2 = make_reagent (fun (a, b) xt ->
  (* pair doesn't propagate an offer — both subcomponents must complete
     synchronously for pair to succeed. *)
  match r1.try_react a xt None with
  | Done c -> (match r2.try_react b xt None with
               | Done d -> Done (c, d)
               | Block -> Block
               | Retry -> Retry)
  | Block -> Block
  | Retry -> Retry)

(* ──────────────────────────────────────────────────────────────────────────
   Execution (two-phase protocol)
   ────────────────────────────────────────────────────────────────────────── *)

(** Two-phase [run]:

    - Phase 1 (no offer): try the reagent. If [Done], commit and return.
      If [Block], go to phase 2. If [Retry] or commit interference, retry.
    - Phase 2 (with offer): create an offer, try again. On [Done], commit
      and return (offer discarded). On [Block], the reagent posted the
      offer to one or more channels — wait for a partner to fulfill it.
      On [Retry], try phase 2 again. *)
let run r a =
  let rec phase1 () =
    let result = Stdlib.ref None in
    (try
      Xt.commit (fun ~xt ->
        match r.try_react a xt None with
        | Done b -> result := Some b
        | Block -> result := None
        | Retry -> result := None; Xt.retry ())
    with _ -> ());
    match !result with
    | Some b -> b
    | None -> phase2 ()

  and phase2 () =
    let offer = make_offer () in
    let result = Stdlib.ref None in
    let snapshot = Stdlib.ref None in
    (try
      Xt.commit (fun ~xt ->
        match r.try_react a xt (Some offer) with
        | Done b -> result := Some b
        | Block ->
          (* Save the xt snapshot so we can install awaiters on read-set
             locations — any change should wake us up to retry. *)
          snapshot := Some (Xt.snapshot ~xt);
          result := None
        | Retry -> result := None; Xt.retry ())
    with _ -> ());
    match !result with
    | Some b -> b  (* Synchronous completion. *)
    | None ->
      (* Install awaiters on read-set locations that will signal the
         offer if anything changes (unblocking upd/cas-style blocks). *)
      (match !snapshot with
       | Some snap -> Xt.install_awaiters snap (fun () -> signal_offer offer)
       | None -> ());
      match await_offer_state offer with
      | Fulfilled v -> v
      | Signaled -> phase1 ()  (* a read-set location changed; retry *)
      | Pending -> assert false
  in
  phase1 ()

(** [run_opt] does phase 1 only — returns [None] if the reagent blocks. *)
let run_opt r a =
  let result = Stdlib.ref None in
  (try
    Xt.commit (fun ~xt ->
      match r.try_react a xt None with
      | Done b -> result := Some b
      | Block -> result := None
      | Retry -> result := None; Xt.retry ())
  with _ -> result := None);
  !result
